name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  building:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup jdk 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Gradle execute permissions
        run: chmod +x gradlew
      - name: Build with gradle
        run: ./gradlew build